#!/bin/bash

CONTAINER_NAME="dist_$(date +%H%M%S_%N)"
echo "Creating container $CONTAINER_NAME"
docker run -itd --rm --mount type=bind,source="$(pwd)",target="/app" --name $CONTAINER_NAME distorage
echo "Starting server. Args: $@"
docker exec --workdir /app $CONTAINER_NAME python main.py server $@
