#!/bin/bash
#
# Runs a client session.

CONTAINER_NAME="dist_$(date +%H%M%S_%N)"
echo "Creating container $CONTAINER_NAME"
docker run -itd --rm --workdir /app --name $CONTAINER_NAME --env PYTHONHASHSEED=0 distorage
echo "Copying files to container"
docker cp . $CONTAINER_NAME:/app/
docker exec -it $CONTAINER_NAME python main.py client
docker attach $CONTAINER_NAME
