#!/bin/bash
#
# This script is used to run a temporal container.

CONTAINER_NAME="dist_$(date +%H%M%S_%N)"
echo "Creating container $CONTAINER_NAME"
docker run -itd --rm --workdir /app --name $CONTAINER_NAME distorage
docker cp . $CONTAINER_NAME:/app
docker attach $CONTAINER_NAME
