"""
This contains global config values for the server.
"""

SERVER_PORT = 8080
CLIENT_PORT = 8081
DHT_PORT = 8082
DHT_STABILIZE_INTERVAL = 2
DHT_FIX_FINGERS_INTERVAL = 2
DHT_CHECK_PREDECESSOR_INTERVAL = 2
DHT_CHECK_SUCCESSOR_INTERVAL = 2
DISOCVER_INTERVAL = 3
DISCOVER_TIMEOUT = 10
